# Generated by Django 4.2.23 on 2025-07-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
    ]
