# Generated by Django 4.2.7 on 2025-07-25 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this recipe",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the recipe", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the recipe"),
                ),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        help_text="Preparation time in minutes"
                    ),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(help_text="Cooking time in minutes"),
                ),
                (
                    "servings",
                    models.PositiveIntegerField(help_text="Number of servings"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Difficulty level of the recipe",
                        max_length=10,
                    ),
                ),
                (
                    "cooking_method",
                    models.CharField(
                        choices=[
                            ("baking", "Baking"),
                            ("frying", "Frying"),
                            ("boiling", "Boiling"),
                            ("grilling", "Grilling"),
                            ("steaming", "Steaming"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Primary cooking method",
                        max_length=10,
                    ),
                ),
                (
                    "ingredients",
                    models.JSONField(help_text="List of ingredients with quantities"),
                ),
                (
                    "instructions",
                    models.JSONField(help_text="Step by step cooking instructions"),
                ),
                (
                    "nutrition_info",
                    models.JSONField(
                        blank=True, help_text="Nutritional information", null=True
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the recipe's main image",
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this recipe is publicly visible",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="List of tags for this recipe"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Recipe version number"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this recipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="recipes_rec_title_9ebae8_idx"),
                    models.Index(
                        fields=["author"], name="recipes_rec_author__e2628b_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="recipes_rec_is_publ_8ba3bf_idx"
                    ),
                    models.Index(
                        fields=["difficulty"], name="recipes_rec_difficu_33131c_idx"
                    ),
                    models.Index(
                        fields=["cooking_method"], name="recipes_rec_cooking_b7124b_idx"
                    ),
                ],
            },
        ),
    ]
