# Generated by Django 4.2.23 on 2025-07-25 22:44

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(
                help_text="List of ingredients with quantities",
                validators=[recipes.models.validate_list],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.JSONField(
                help_text="Step by step cooking instructions",
                validators=[recipes.models.validate_list],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="nutrition_info",
            field=models.JSONField(
                blank=True,
                help_text="Nutritional information",
                null=True,
                validators=[recipes.models.validate_dict],
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.JSONField(
                default=list,
                help_text="List of tags for this recipe",
                validators=[recipes.models.validate_list],
            ),
        ),
    ]
