# Generated by Django 4.2.23 on 2025-07-25 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_fix_category_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
    ]
