# Generated by Django 4.2.7 on 2025-07-25 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0006_remove_slug_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this rating",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating value from 1 to 5 stars",
                        validators=[recipes.models.validate_rating],
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True, help_text="Optional review text", max_length=2000
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this rating is from a verified user who made the recipe",
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of users who found this review helpful",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Recipe being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this rating",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rating",
                "verbose_name_plural": "ratings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipe"], name="recipes_rat_recipe__263c1e_idx"
                    ),
                    models.Index(
                        fields=["user"], name="recipes_rat_user_id_05e6e5_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="recipes_rat_rating_8a4c09_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="recipes_rat_created_462957_idx"
                    ),
                    models.Index(
                        fields=["helpful_count"], name="recipes_rat_helpful_6bde2d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_recipe_user_rating"
            ),
        ),
    ]
