# Generated by Django 4.2.7 on 2025-07-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_rating_rating_unique_recipe_user_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="review",
            field=models.CharField(
                blank=True, help_text="Optional review text", max_length=2000
            ),
        ),
    ]
