# Generated by Django 4.2.23 on 2025-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_recipeview_userfavorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="moderation_notes",
            field=models.TextField(
                blank=True, help_text="Notes from moderators about this recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged for Review"),
                ],
                default="draft",
                help_text="Current moderation status of the recipe",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["moderation_status"], name="recipes_rec_moderat_dd665d_idx"
            ),
        ),
    ]
